apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dqe5
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0069-tenant/tkrw-pr712-0075-0069-app/devfile-sample-dqe5@sha256:f9d519f7fe5177c8b5183700f3c214089980a958b258ac286e926fc336ee0ef9
        name: my-nodejs
        resources: {}
status: {}
